// src/ds-suite/libs/ui/src/lib/components/display-status/display-status.component.ts
// SPDX-FileCopyrightText: © 2014 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { Component, OnInit, Input } from '@angular/core'
import { DisplayStatus } from '@ds-suite/model'

@Component({
  selector: 'display-status',
  templateUrl: './display-status.component.html',
  styleUrls: ['./display-status.component.css']
})
export class DisplayStatusComponent implements OnInit {
  _status: DisplayStatus
  _description: string

  @Input()
  set status (status: DisplayStatus) { this._status = status }

  get status (): DisplayStatus { return this._status }

  @Input()
  set description (description: string) { this._description = description }

  get description (): string { return this._description }

  constructor () { }

  ngOnInit () {
  }

  DisplayStatusToString (stat: DisplayStatus): string {
    let rval: string = ''
    switch (stat) {
      case DisplayStatus.Unknown:
        rval = 'unbekannt'
        break
      case DisplayStatus.Active:
        rval = 'aktiv'
        break
      case DisplayStatus.Online:
        rval = 'angeschaltet'
        break
      case DisplayStatus.Offline:
        rval = 'ausgeschaltet'
        break
    }
    return rval
  }
}

<span  [ngClass]="{'ds-bg-yellow':(status < 0), 'ds-bg-red': (status === 0), 'ds-bg-green': (status >= 1)}">
  {{ description }}
  {{DisplayStatusToString(status)}}
</span>

// src/ds-webapps/src/components/DisplayStatus.vue
<script lang="ts">
// SPDX-FileCopyrightText: © 2019 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { defineComponent } from 'vue'

export default defineComponent({
  props:{
    status: {type: Number/*Object as PropType<DisplayStatus>*/, required: true},
    description: {type: String, required: true}
  },
  computed: {
    DisplayStatusToString(): string {
    let rval: string = 'Status: '
    switch (this.status) {
      case -1:
        rval += 'unbekannt'
        break
      case 2:
        rval += 'aktiv'
        break
      case 1:
        rval += 'angeschaltet'
        break
      case 0:
        rval += 'ausgeschaltet'
    }
    return rval
  }
  }
})
</script>

<template>
  <span :class="{'ds-bg-yellow':(status < 0), 'ds-bg-red': (status === 0), 'ds-bg-green': (status >= 1)}">
    {{ description }}
    {{ DisplayStatusToString }}
  </span>
</template>

<style lang="stylus" scoped>
.ds-bg-yellow
    color yellow

.ds-bg-red
    color red

.ds-bg-green
    color green
</style>
