// src/ds-suite/apps/roomcontrol/src/app/display-control/display-control.component.ts
import { Component, Input, OnInit, ViewChild } from '@angular/core';

import { Display, DisplayStatus } from '@ds-suite/model';
import { DisplayService } from '@ds-suite/core';

import { DisplayDialogComponent } from '../display-dialog/display-dialog.component';

@Component({
  selector: 'app-display-control',
  templateUrl: './display-control.component.html',
  styleUrls: ['./display-control.component.css']
})
export class DisplayControlComponent implements OnInit {
  _display: Display;
  screenshot: String;
  status: DisplayStatus;
  @ViewChild(DisplayDialogComponent) modal: DisplayDialogComponent;

  constructor(private displayService: DisplayService) { }

  @Input()
  set display(display: Display) {
    this._display = display;
    this.displayService.getDisplayStatus(this._display)
      .subscribe(response => {
        this.status = response
        this.updateScreenshot();
      });
  }
  get display(): Display { return this._display; }

  updateScreenshot() {
    if (this.status === DisplayStatus.Offline)
      this.screenshot = '/assets/img/offline.jpg'
    else if (this.status === DisplayStatus.Online)
      this.screenshot = `${this.display.controlUrl}/api/screenshot`;
    else
      this.screenshot = '/assets/img/unknown.jpg';
  }

  ngOnInit() {
  }

  DisplayStatusToString(stat: DisplayStatus) : string {
    var rval : string ="";
    switch (stat) {
      case DisplayStatus.Unknown:
        rval="unbekannt"
        break;
      case DisplayStatus.Active:
        rval="aktiv"
        break;
      case DisplayStatus.Online:
        rval="angeschaltet"
        break;
      case DisplayStatus.Offline:
        rval="ausgeschaltet"
        break;
      }
      return rval;
  }

}

<div class="card" *ngIf="display">
  <div class="card-header">
    Anzeigegerät {{ display.name }}
  </div>
  <div class="card-img"  id="ScreenshotImage" (window:resize)="onResize($event)" *ngIf="screenshot">
    <img [src]="screenshot" (click)="modal.open(screenshot)" class="img-middle-proportion" [style.height.px]="ImageHeight" >
  </div>
  <div class="card-block" [ngClass]="{'ds-bg-yellow':(status < 0), 'ds-bg-red': (status === 0), 'ds-bg-green': (status >= 1)}">
    <div class="card-text">
      Status: {{DisplayStatusToString(status)}}
    </div>
  </div>
  <div class="card-footer">
    <button class="btn btn-sm btn-link" *ngIf="(status < 1)" (click)="startClick()"><clr-icon shape="play"></clr-icon> Anschalten</button>
    <button class="btn btn-sm btn-link" *ngIf="(status >= 1)" (click)="updateClick()"><clr-icon shape="refresh"></clr-icon> Aktualisieren</button>
    <button class="btn btn-sm btn-link" *ngIf="(status >= 1)" (click)="shutdownClick()"><clr-icon shape="power"></clr-icon> Ausschalten</button>
    <button class="btn btn-sm btn-link" *ngIf="(status >= 1)" (click)="restartClick()"><clr-icon shape="replay-all"></clr-icon> Neu starten</button>
  </div>
</div>


<app-display-dialog></app-display-dialog>

// src/ds-webapps/roomcontrol/components/DisplayControl.vue
<script lang="ts">
// SPDX-FileCopyrightText: © 2019 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { defineComponent } from 'vue'
import Display from '../../src/models/Display'
import DisplayStatus from '../../src/components/DisplayStatus.vue'

export default  defineComponent({
  components: {DisplayStatus},
  setup(){
    return {
      status: 0,
      screenshot: '',
      ImageHeight: 0,
      display: {} as Display,
      displays:[] as Display[]
    }
  },
  methods: {
    async startClick(){ },
    async updateClick(){ },
    async shutdownClick(){ },
    async restartClick(){ }
  }
})
</script>

<template>
  <div class="card" v-if="display">
  <div class="card-header">
    Anzeigegerät {{ display.name }}
  </div>
  <div class="card-img"  id="ScreenshotImage" v-if="screenshot">
    <img :src="screenshot" @click="modal.open(screenshot)" class="img-middle-proportion" :style="{height: ImageHeight+'px'}">
  </div>
  <div class="card-block">
    <div class="card-text">
      <DisplayStatus :status="status" :description="'Status: '" />
    </div>
  </div>
  <div class="card-footer">
    <button class="btn btn-sm btn-link" v-if="(status < 1)" @click="startClick()"><clr-icon shape="play"></clr-icon> Anschalten</button>
    <button class="btn btn-sm btn-link" v-if="(status >= 1)" @click="updateClick()"><clr-icon shape="refresh"></clr-icon> Aktualisieren</button>
    <button class="btn btn-sm btn-link" v-if="(status >= 1)" @click="shutdownClick()"><clr-icon shape="power"></clr-icon> Ausschalten</button>
    <button class="btn btn-sm btn-link" v-if="(status >= 1)" @click="restartClick()"><clr-icon shape="replay-all"></clr-icon> Neu starten</button>
  </div>
</div>


<app-display-dialog></app-display-dialog>
</template>
