// src/ds-suite/apps/roomcontrol/src/app/termine/termine.component.ts
// SPDX-FileCopyrightText: © 2014 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { Component, Input, OnInit, OnDestroy, AfterViewInit, ViewChild } from '@angular/core'

import { timer } from 'rxjs'
import { Subscription } from 'rxjs/Subscription'
import 'rxjs/add/operator/switchMap'
import 'rxjs/add/observable/timer'

import { Termin, TerminStatus } from '@ds-suite/model'

import { TerminService } from '@ds-suite/core'
import { ClrDatagrid } from '@clr/angular'
import { JsonConfigService } from '@ds-suite/backend/src'
import { AppConfigRoomcontrol } from '@ds-suite/model/src/lib/app-config'

@Component({
  selector: 'app-termine',
  templateUrl: './termine.component.html',
  styleUrls: ['./termine.component.css']
})
export class TermineComponent implements OnInit, OnDestroy, AfterViewInit {
  private updateTimer: any
  private updateSub: Subscription
  @ViewChild('DataGridTermine', { static: true }) DataGridTermine: ClrDatagrid
  loadingTermine: boolean = true
  _displayName: string
  termine: Termin[]
  showBesetzung: boolean = false

  GetStatausValues (): string[] {
    return Object.values(TerminStatus)
  }

  constructor (
    private readonly terminService: TerminService, private readonly jsonConfigService: JsonConfigService) {
    const config = jsonConfigService.getConfig() as AppConfigRoomcontrol
    this.showBesetzung = Boolean(config.showBesetzung)
  }

  @Input()
  set displayName (displayName: string) {
    this._displayName = displayName
    this.loadTermine()
  }

  get displayName (): string { return this._displayName }

  loadTermine () {
    this.terminService.getTermine(this.displayName)
      .subscribe(termine => {
        this.termine = this.sortTermine(termine)
        this.loadingTermine = false
      })
  }

  sortTermine (termine: Termin[]): Termin[] {
    return termine.sort((t1, t2) => {
      if (t1.uhrzeitAktuell > t2.uhrzeitAktuell) {
        return 1
      } else if (t1.uhrzeitAktuell < t2.uhrzeitAktuell) {
        return -1
      }
      return 0
    })
  }

  changeOeffentlich (termin: Termin) {
    if (termin.oeffentlich === 'ja') { termin.oeffentlich = 'nein' } else { termin.oeffentlich = 'ja' }

    this.terminService.saveTermin(termin).subscribe(val => { },
      err => {
        console.error(err)
      })
  }

  changeStatus (termin: Termin) {
    this.terminService.saveTermin(termin).subscribe(val => { },
      err => {
        console.error(err)
      })
  }

  ngOnInit () {
  }

  onResize (event) {
    this.DataGridTermine.resize()
  }

  onSubmit () {
  }

  ngAfterViewInit (): void {
    this.updateTimer = timer(5000, 10000)
    this.updateSub = this.updateTimer.subscribe((t: any) => {
      this.loadTermine()
    })
  }

  ngOnDestroy () {
    this.updateSub.unsubscribe()
  }
}


<!--h1>Termine</h1-->
<form>
  <clr-datagrid #DataGridTermine (window:resize)="onResize($event)" [clrDgLoading]="loadingTermine">

    <clr-dg-column class="ds-termin-column-uhrzeit">Uhrzeit</clr-dg-column>
    <clr-dg-column class="ds-termin-column-az">Aktenzeichen</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Aktivpartei</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Passivpartei</clr-dg-column>
    <clr-dg-column *ngIf="showBesetzung" class="ds-termin-column-partei">Besetzung</clr-dg-column>
    <clr-dg-column class="ds-termin-column-oeffentlich">Öffentlich</clr-dg-column>
    <clr-dg-column class="ds-termin-column-status">Status</clr-dg-column>

    <clr-dg-placeholder>Es sind keine Termine vorhanden</clr-dg-placeholder>
    <clr-dg-row *clrDgItems="let termin of termine; let i = index">
      <clr-dg-cell class="ds-termin-column-uhrzeit">{{ termin.uhrzeitAktuell }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-az">{{ termin.az }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienAktivKurz }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienPassivKurz }}</clr-dg-cell>
      <clr-dg-cell *ngIf="showBesetzung" class="ds-termin-column-partei">{{ termin.besetzung }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-oeffentlich">
        <div class="toggle-switch">
          <input [id]="'chk_oeff_' + i" clrToggle type="checkbox" [checked]="termin.oeffentlich | yesnoBoolean" (change)="changeOeffentlich(termin)">
          <label [for]="'chk_oeff_' + i"></label>
        </div>
      </clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-status">
        <clr-select-container>
          <select clrSelect [name]="'sel_status_' + i" [id]="'sel_status_' + i" [(ngModel)]="termin.status" (ngModelChange)="changeStatus(termin)">
            <option *ngFor="let status of GetStatausValues()" [value]="status">{{ status }}</option>
          </select>
        </clr-select-container>
      </clr-dg-cell>
    </clr-dg-row>
  </clr-datagrid>
</form>

// src/ds-webapps/roomcontrol/components/Termine.vue
<script lang="ts">
// SPDX-FileCopyrightText: © 2019 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { defineComponent } from 'vue'
import Termin from '../../src/models/Termin'
import DisplayStatus from '../../src/components/DisplayStatus.vue'

export default  defineComponent({
  components: {DisplayStatus},
  setup(){
    return {
      loadingTermine: true,
      _displayName: '',
      termine: [] as Termin[],
      showBesetzung: false
    }
  },
  props: ['displayName'],
  methods: {
    async changeOeffentlich(termin: Termin){
      if (termin.oeffentlich === 'ja') { termin.oeffentlich = 'nein' } else { termin.oeffentlich = 'ja' }

      this.terminService.saveTermin(termin).subscribe(val => { },
        err => {
          console.error(err)
        })
    },
    async changeStatus(termin: Termin){
      this.terminService.saveTermin(termin).subscribe(val => { },
      err => {
        console.error(err)
      })
    }
  },
  mounted(){

  }
})
</script>


<template>
  <form>
  <clr-datagrid #DataGridTermine (window:resize)="onResize($event)" [clrDgLoading]="loadingTermine">

    <clr-dg-column class="ds-termin-column-uhrzeit">Uhrzeit</clr-dg-column>
    <clr-dg-column class="ds-termin-column-az">Aktenzeichen</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Aktivpartei</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Passivpartei</clr-dg-column>
    <clr-dg-column *ngIf="showBesetzung" class="ds-termin-column-partei">Besetzung</clr-dg-column>
    <clr-dg-column class="ds-termin-column-oeffentlich">Öffentlich</clr-dg-column>
    <clr-dg-column class="ds-termin-column-status">Status</clr-dg-column>

    <clr-dg-placeholder>Es sind keine Termine vorhanden</clr-dg-placeholder>
    <clr-dg-row v-for="(termin, i) of termine" :key="'termine'+i">
      <clr-dg-cell class="ds-termin-column-uhrzeit">{{ termin.uhrzeitAktuell }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-az">{{ termin.az }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienAktivKurz }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienPassivKurz }}</clr-dg-cell>
      <clr-dg-cell *ngIf="showBesetzung" class="ds-termin-column-partei">{{ termin.besetzung }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-oeffentlich">
        <div class="toggle-switch">
          <input :id="'chk_oeff_' + i" clrToggle type="checkbox" :checked="!!termin.oeffentlich" @change="changeOeffentlich(termin)">
          <label :for="'chk_oeff_' + i"></label>
        </div>
      </clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-status">
        <clr-select-container>
          <select clrSelect :name="'sel_status_' + i" :id="'sel_status_' + i" v-model="termin.status" @ngModelChange="changeStatus(termin)">
            <option v-for="(status, idx) of GetStatausValues()" :key="'valu'+idx" :value="status">{{ status }}</option>
          </select>
        </clr-select-container>
      </clr-dg-cell>
    </clr-dg-row>
  </clr-datagrid>
</form>

</template>
