// src/ds-webapps/roomcontrol/components/Termine.vue
<script lang="ts">
// SPDX-FileCopyrightText: © 2019 Oberverwaltungsgericht Rheinland-Pfalz <poststelle@ovg.jm.rlp.de>
// SPDX-License-Identifier: EUPL-1.2
import { defineComponent } from 'vue'
import Termin from '../../src/models/Termin'
import DisplayStatus from '../../src/components/DisplayStatus.vue'

export default  defineComponent({
  components: {DisplayStatus},
  setup(){
    return {
      loadingTermine: true,
      _displayName: '',
      termine: [] as Termin[],
      showBesetzung: false
    }
  },
  props: ['displayName'],
  methods: {
    async changeOeffentlich(termin: Termin){
      if (termin.oeffentlich === 'ja') { termin.oeffentlich = 'nein' } else { termin.oeffentlich = 'ja' }

      this.terminService.saveTermin(termin).subscribe(val => { },
        err => {
          console.error(err)
        })
    },
    async changeStatus(termin: Termin){
      this.terminService.saveTermin(termin).subscribe(val => { },
      err => {
        console.error(err)
      })
    }
  },
  mounted(){

  }
})
</script>


<template>
  <form>
  <clr-datagrid #DataGridTermine (window:resize)="onResize($event)" [clrDgLoading]="loadingTermine">

    <clr-dg-column class="ds-termin-column-uhrzeit">Uhrzeit</clr-dg-column>
    <clr-dg-column class="ds-termin-column-az">Aktenzeichen</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Aktivpartei</clr-dg-column>
    <clr-dg-column class="ds-termin-column-partei">Passivpartei</clr-dg-column>
    <clr-dg-column *ngIf="showBesetzung" class="ds-termin-column-partei">Besetzung</clr-dg-column>
    <clr-dg-column class="ds-termin-column-oeffentlich">Öffentlich</clr-dg-column>
    <clr-dg-column class="ds-termin-column-status">Status</clr-dg-column>

    <clr-dg-placeholder>Es sind keine Termine vorhanden</clr-dg-placeholder>
    <clr-dg-row v-for="(termin, i) of termine" :key="'termine'+i">
      <clr-dg-cell class="ds-termin-column-uhrzeit">{{ termin.uhrzeitAktuell }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-az">{{ termin.az }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienAktivKurz }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienPassivKurz }}</clr-dg-cell>
      <clr-dg-cell *ngIf="showBesetzung" class="ds-termin-column-partei">{{ termin.besetzung }}</clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-oeffentlich">
        <div class="toggle-switch">
          <input :id="'chk_oeff_' + i" clrToggle type="checkbox" :checked="!!termin.oeffentlich" @change="changeOeffentlich(termin)">
          <label :for="'chk_oeff_' + i"></label>
        </div>
      </clr-dg-cell>
      <clr-dg-cell class="ds-termin-column-status">
        <clr-select-container>
          <select clrSelect :name="'sel_status_' + i" :id="'sel_status_' + i" v-model="termin.status" @ngModelChange="changeStatus(termin)">
            <option v-for="(status, idx) of GetStatausValues()" :key="'valu'+idx" :value="status">{{ status }}</option>
          </select>
        </clr-select-container>
      </clr-dg-cell>
    </clr-dg-row>
  </clr-datagrid>
</form>

</template>

// src/ds-suite/apps/dsmanager/src/app/termine/termine.component.ts
import { Component, OnInit, ViewChild } from '@angular/core';

import { Display } from '@ds-suite/model';
import { DisplayService } from '@ds-suite/core';

import { Termin } from '@ds-suite/model';
import { TerminStatus } from '@ds-suite/model';
import { TerminService } from '@ds-suite/core';
import { ClrDatagrid } from '@clr/angular';

@Component({
  selector: 'termine',
  templateUrl: './termine.component.html',
  styleUrls: ['./termine.component.css']
})
export class TermineComponent implements OnInit {
  termine: Termin[];
  filteredTermine: Termin[];
  loadingTermine: boolean = true;
  public selStatus: boolean[] = [false, false, false, false, false];
  public selGericht: boolean[] = [];
  public selSaal: boolean[] = [];
  @ViewChild('DataGridTermine') DataGridTermine: ClrDatagrid;

  constructor(private terminService: TerminService) { }

  changeSelection() {
    //console.log("selStatus:",this.selStatus)
    //console.log("selGericht:",this.selGericht)
    //console.log("selSaal:",this.selSaal)
    this.filterTermine();
  }

  filterTermine() {
    this.filteredTermine=[];
    var i:number;
    var selStatus: string[] = [];
    var selGericht: string[] = [];
    var selSaal: string[] = [];

    var statusValues: string[] = Object.values(TerminStatus);
    var gerichtValues: string[] = this.GetGerichtValues();
    var saalValues: string[] = this.GetSaalValues();

    for (i=0; i<this.selStatus.length; i++) {
      if (this.selStatus[i]==true){
        selStatus.push(statusValues[i]);
      }
    }
    for (i=0; i<this.selGericht.length; i++) {
      if (this.selGericht[i]==true){
        selGericht.push(gerichtValues[i]);
      }
    }
    for (i=0; i<this.selSaal.length; i++) {
      if (this.selSaal[i]==true){
        selSaal.push(saalValues[i]);
      }
    }
    
    this.filteredTermine=this.termine.filter(t=> {
      console.log("selStatus",selStatus)
      console.log("t.status",t.status)
      if (selStatus.length>0 && selStatus.indexOf(t.status)<0)
        return false;
      if (selGericht.length>0 && selGericht.indexOf(t.gericht)<0)
        return false;
      if (selSaal.length>0 && selSaal.indexOf(t.sitzungssaal)<0)
        return false; 
      return true;
    });

  }

  GetStatusValues() : Array<string> {
    return Object.keys(TerminStatus)
  }

  GetGerichtValues() : Array<string> {
    if (this.termine==undefined) return [];
    return  Array.from(new Set(this.termine.map(t => t.gericht)));
  }

  GetSaalValues() : Array<string> {
    if (this.termine==undefined) return [];
    return  Array.from(new Set(this.termine.map(t => t.sitzungssaal)));
  }
  
  loadTermine() {
    this.terminService.getTermine("NJZ-Foyer-Gesamt")
      .subscribe(termine => {
        this.termine = termine;
        this.InitSaalSelection();
        this.InitGerichtSelection();
        this.filterTermine()
        this.loadingTermine=false;
      },
      err => {
        console.error("Termine konnten nicht geladen werden: ",err);
      });
  }

  InitSaalSelection(){
    this.GetSaalValues().forEach(element => {
      this.selSaal.push(false);
    });
  }

  
  InitGerichtSelection(){
    this.GetGerichtValues().forEach(element => {
      this.selGericht.push(false);
    });
  }

  onResize(event) {
    this.DataGridTermine.resize();
  }

  ngOnInit() {
    this.loadTermine();
  }

}

<div class="main-container">
    <div class="content-container">
        <nav class="sidenav">
            <section class="sidenav-content">
                <!--Selektion nach Status-->
                <section class="nav-group">
                    <input id="tabStatus" type="checkbox">
                    <label for="tabStatus">Status</label>
                    <ul class="nav-list">
                        <div *ngFor="let status of GetStatusValues(); let index = index;">
                            <clr-checkbox
                            [clrInline]="true"
                            [name]="'sel_status_' + index"  
                                    [id]="'sel_status_' + index"
                                    [(clrChecked)]="selStatus[index]"
                                    (change)="changeSelection()">
                                    {{status}}
                            </clr-checkbox>
                        </div>
                    </ul>
                </section>
                <!--Selektion nach Gericht-->
                <section class="nav-group">
                    <input id="tabGericht" type="checkbox">
                    <label for="tabGericht">Gericht</label>
                    <ul class="nav-list">
                        <div *ngFor="let gericht of GetGerichtValues(); let index = index;">
                            <clr-checkbox
                            [clrInline]="true"
                            [name]="'sel_gericht_' + index"  
                                    [id]="'sel_gericht_' + index"
                                    [(clrChecked)]="selGericht[index]"
                                    (change)="changeSelection()">
                                    {{gericht}}
                            </clr-checkbox>
                        </div>
                    </ul>
                </section>
                <!--Selektion nach Saal-->
                <section class="nav-group">
                    <input id="tabSaal" type="checkbox">
                    <label for="tabSaal">Saal</label>
                    <ul class="nav-list">
                        <div *ngFor="let saal of GetSaalValues(); let index = index;">
                            <clr-checkbox
                                [clrInline]="true"
                                [name]="'sel_saal_' + index"  
                                [id]="'sel_saal_' + index"
                                [(clrChecked)]="selSaal[index]"
                                (change)="changeSelection()">
                                {{saal}}
                            </clr-checkbox>
                        </div>
                    </ul>
                </section>

            </section>
          </nav>  
      <div class="content-area">
        
        <clr-datagrid #DataGridTermine  (window:resize)="onResize($event)" [clrDgLoading]="loadingTermine">

            <clr-dg-column class="ds-termin-column-uhrzeit">Uhrzeit</clr-dg-column>
            <clr-dg-column class="ds-termin-column-gericht">Gericht</clr-dg-column>
            <clr-dg-column class="ds-termin-column-saal">Saal</clr-dg-column>
            <clr-dg-column class="ds-termin-column-az">Aktenzeichen</clr-dg-column>
            <clr-dg-column class="ds-termin-column-partei">Aktivpartei</clr-dg-column>
            <clr-dg-column class="ds-termin-column-partei">Passivpartei</clr-dg-column>
            <clr-dg-column class="ds-termin-column-oeffentlich">Öffentlich</clr-dg-column>
            <clr-dg-column class="ds-termin-column-status">Status</clr-dg-column>
        
            <clr-dg-placeholder>Zu dieser Selektion sind keine Termine vorhanden</clr-dg-placeholder>
            <clr-dg-row *clrDgItems="let termin of filteredTermine; let i = index">
              <clr-dg-cell class="ds-termin-column-uhrzeit">{{ termin.uhrzeitAktuell }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-gericht">{{ termin.gericht }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-saal">{{ termin.sitzungssaal }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-az">{{ termin.az }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienAktivKurz }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-partei">{{ termin.parteienPassivKurz }}</clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-oeffentlich">
                <div class="toggle-switch">
                  <input [id]="'chk_oeff_' + i" type="checkbox" [checked]="termin.oeffentlich | yesnoBoolean" disabled>
                  <label [for]="'chk_oeff_' + i"></label>
                </div>
              </clr-dg-cell>
              <clr-dg-cell class="ds-termin-column-status">{{termin.status}}</clr-dg-cell>
            </clr-dg-row>
          </clr-datagrid>

        
    </div>
</div>
